# This is a basic workflow to help you get started with Actions

name: Bridgecrew

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   bridgecrew:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Scan Iac with kics
      - name: run kics Scan
        uses: checkmarx/kics-github-action@v1.7.0
        with:
          # scanning two directories: ./terraform/ ./cfn-templates/ plus a single file
          path: 'terraform,cfn-templates'
          output_path: myResults/
      # Display the results in json format
      - name: display kics results
        run: |
          cat myResults/results.json
